from app.models.models import (
    User,
    RiskZone,
    CitizenReport,
    WeatherData,
    FloodPrediction,
    Shelter,
    Road,
    Village,
    ResourceCenter,
    Alert,
    SatelliteImage,
    DamageReport,
    all_models,
)
